# Generated by Django 4.1.2 on 2022-10-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_docctor',
            new_name='is_doctor',
        ),
    ]
