# Generated by Django 4.1.2 on 2022-10-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_add_department_add_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Department',
        ),
        migrations.DeleteModel(
            name='Add_Doctor',
        ),
    ]
