# Generated by Django 4.1.2 on 2022-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='provider_order_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
