# Generated by Django 4.1.2 on 2022-11-01 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=500)),
                ('morning', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')])),
                ('afternoon', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')])),
                ('evening', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')])),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Number of days cannot be negative')])),
            ],
        ),
    ]
