# Generated by Django 4.1.2 on 2022-11-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='afternoon',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='days',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='evening',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='morning',
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
