# Generated by Django 4.1.2 on 2022-11-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_medicine_afternoon_remove_medicine_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
