# Generated by Django 4.1.2 on 2022-11-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_medicine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
