# Generated by Django 4.1.2 on 2022-11-01 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_medicine_afternoon_remove_medicine_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0002_remove_doctor_email_remove_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=200)),
                ('morning', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')])),
                ('afternoon', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')])),
                ('evening', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')])),
                ('days', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of days cannot be negative')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
