# Generated by Django 4.1.2 on 2022-11-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulation',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine'),
        ),
    ]
