# Generated by Django 4.1.2 on 2022-11-10 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_consulation_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary', models.CharField(max_length=250)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.consulation')),
            ],
        ),
    ]
