# Generated by Django 4.1.2 on 2022-11-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_consulation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulation',
            old_name='evening',
            new_name='night',
        ),
    ]
