# Generated by Django 4.1.2 on 2022-11-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
