# Generated by Django 4.1.2 on 2022-11-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_rename_evening_consulation_night'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulation',
            old_name='user',
            new_name='patient',
        ),
    ]
