# Generated by Django 4.1.2 on 2022-11-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_rename_user_consulation_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulation',
            old_name='patient',
            new_name='user',
        ),
    ]
