# Generated by Django 4.1.2 on 2022-11-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_rename_patient_consulation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulation',
            old_name='user',
            new_name='patient',
        ),
    ]
