# Generated by Django 4.1.2 on 2022-11-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_blood_group'),
        ('doctor', '0009_rename_user_consulation_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulation',
            name='medicine',
        ),
        migrations.AlterField(
            model_name='consulation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
