# Generated by Django 4.1.2 on 2022-11-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_patient_appointment_user'),
        ('doctor', '0010_remove_consulation_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='consulation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='consulation',
            name='symptoms',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
