# Generated by Django 4.1.2 on 2022-11-04 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0011_alter_consulation_doctor_alter_consulation_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
