# Generated by Django 4.1.2 on 2022-11-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_consulation_afternoon_alter_consulation_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
