# Generated by Django 4.1.2 on 2022-11-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_consulation_medicine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_patient_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('1', '09:00 – 10:00'), ('2', '10:00 – 11:00'), ('3', '11:00 – 12:00'), ('4', '12:00 – 13:00'), ('5', '13:00 – 14:00'), ('6', '14:00 – 15:00'), ('7', '15:00 – 16:00'), ('8', '16:00 – 17:00'), ('9', '17:00 – 18:00')], max_length=50, null=True),
        ),
    ]
