# Generated by Django 4.1.2 on 2022-11-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_appointment_age_remove_appointment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
