# Generated by Django 4.1.2 on 2022-11-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appointment_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='user',
        ),
    ]
